export const TYPEORM_CONNECTION = "TYPEORM_CONNECTION";

export const TYPEORM_HOST = "TYPEORM_HOST";

export const TYPEORM_USERNAME = "TYPEORM_USERNAME";

export const TYPEORM_PASSWORD = "TYPEORM_PASSWORD";

export const TYPEORM_DATABASE = "TYPEORM_DATABASE";

export const TYPEORM_PORT = "TYPEORM_PORT";

export const TYPEORM_URL = "TYPEORM_URL";

export const TYPEORM_SYNCHRONIZE = "TYPEORM_SYNCHRONIZE";

export const TYPEORM_LOGGING = "TYPEORM_LOGGING";

export const TYPEORM_ENTITIES = "TYPEORM_ENTITIES";

export const TYPEORM_MIGRATIONS_DIR = "TYPEORM_MIGRATIONS_DIR";

export const TYPEORM_MIGRATIONS = "TYPEORM_MIGRATIONS";
