version: "3.3"

services:
  service-nest:
    build:
      dockerfile: Dockerfile
      context: .
    restart: always
    environment:
      - DATABASE_TYPE=postgres
      - DATABASE_URL=postgres://postgres:password@service-db:5432/postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DATABASE=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
    container_name: service-nest
    env_file:
      - .env
    depends_on:
      - service-db
    volumes:
      - ./src:/app/src
      - .env:/app/.env
    ports:
      - "3000:3000"

  service-db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
    container_name: service-db
    volumes:
      - ./environment/volumes:/var/lib/postgresql/data
    ports:
      - "5432:5432"
